### ISSUE TITLE
SerialComm reconciliation 

### ISSUE THREAD

**Issue by MisterMartin** [kalnajslab-org/StratoCore_RATS#7]
There are two conflicting repositories for SerialComm: _kalnajslab-org/SerialComm_ and _dastcvi/SerialComm_. 

_kalnajslab-org/SerialComm_ doesn't work with MCB_4.1, with the error:
```
'class MCBComm' has no member named 'string_rx'
'STRING_MESSAGE' was not declared in this scope
```
It does compile with _dastcvi/SerialComm_.

_kalnajslab-org/SerialComm_:
  - was forked from _dastcvi/SerialComm_ on 2019-09-24. 
  - Checksums for binary messages were added on 2019-10-22.
  - Is 2 commits ahead of _dastcvi/SerialComm_ (binary checksum addition)
  - Is 10 commits behind _dastcvi/SerialComm_. (These commits define STRING_MESSAGE)

_dastcvi/SerialComm_:
  - Critical read bugs were fixed in later commits.
  - The string message type was added in later commits.
  - Checksum was added in later commits.

***Which repository should we be using?   
     Could this explain why the StratoCore_RATS GETMCBEEPROM telecommand and is not working?***

**Comment by MisterMartin** [comment]
Use (fork) dastcvi/SerialComm. Lars old repo is not valid.

Check baud rate (in SerialComm).

**Comment by MisterMartin** [comment]
The kalnajslab-org/SerialComm (nee kalnajslab/SerialComm) repo was out of date, and not relevant. It was renamed as kalnajslab-org/SerialComm-LarsObsolete. It can probably be deleted in the future, but it does contain code for some sort of checksum calculation.

dastcvi/SerialComm was forked to kalnajslab-org/SerialComm.
